export const admin = {
  uri: "http://onto.fel.cvut.cz/ontologies/record-manager/Admin-Administratorowitch-9387",
  firstName: "Admin",
  lastName: "Administratorowitch",
  username: "admin",
  emailAddress: "admin@gmail.com",
  isInvited: true,
  institution: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/institution/instance1036853597",
    key: "322055167059439587",
    name: "admin_institution",
    members: [],
  },
  roleGroup: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/admin-role-group",
    name: "admin-role-group",
    roles: [
      "publishRecords",
      "readStatistics",
      "writeAllUsers",
      "commentRecordQuestions",
      "rejectRecords",
      "importCodelists",
      "readAllRecords",
      "writeOrganizationRecords",
      "readOrganization",
      "readAllOrganizations",
      "writeAllRecords",
      "readOrganizationUsers",
      "writeOrganization",
      "readAllUsers",
      "completeRecords",
      "readOrganizationRecords",
      "readActionHistory",
      "writeAllOrganizations",
      "writeOrganizationUsers",
    ],
  },
  impersonated: false,
  roles: [
    "publishRecords",
    "readStatistics",
    "writeAllUsers",
    "commentRecordQuestions",
    "rejectRecords",
    "importCodelists",
    "readAllRecords",
    "writeOrganizationRecords",
    "readOrganization",
    "readAllOrganizations",
    "writeAllRecords",
    "readOrganizationUsers",
    "writeOrganization",
    "readAllUsers",
    "completeRecords",
    "readOrganizationRecords",
    "readActionHistory",
    "writeAllOrganizations",
    "writeOrganizationUsers",
  ],
};

export const entryClerk = {
  uri: "http://onto.fel.cvut.cz/ontologies/record-manager/Daniil-Palagin-9060",
  firstName: "EntryClerk",
  lastName: "EntryClerkorovitch",
  username: "entryClerk",
  emailAddress: "entryClerk@gmail.com",
  isInvited: true,
  institution: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/institution/instance1036853597",
    key: "322055167059439587",
    name: "admin_institution",
    members: [],
  },
  roleGroup: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/entry-clerk-role-group",
    name: "entry-clerk-role-group",
    roles: ["readOrganizationRecords", "commentRecordQuestions", "readOrganization"],
  },
  impersonated: false,
  roles: ["readOrganizationRecords", "commentRecordQuestions", "readOrganization"],
};

export const reviewer = {
  uri: "http://onto.fel.cvut.cz/ontologies/record-manager/Daniil-Palagin-9060",
  firstName: "Reviewer",
  lastName: "Reviewerevitch",
  username: "reviewer",
  emailAddress: "reviewer@gmail.com",
  isInvited: true,
  institution: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/institution/instance1036853597",
    key: "322055167059439587",
    name: "admin_institution",
    members: [],
  },
  roleGroup: {
    uri: "http://onto.fel.cvut.cz/ontologies/record-manager/reviewer-role-group",
    name: "reviewer-role-group",
    roles: ["completeRecords", "commentRecordQuestions"],
  },
  impersonated: false,
  roles: ["completeRecords", "commentRecordQuestions"],
};

export const ROLE_GROUPS = [
  "admin-role-group",
  "entry-clerk-role-group",
  "reviewer-role-group",
  "data-collection-coordinator-role-group",
  "organization-manager-role-group",
];
